services:
  - type: web
    name: blind-ai-backend
    env: python
    region: oregon
    plan: free # Starter plan or higher is recommended for PyTorch memory requirements
    buildCommand: "pip install --upgrade pip && pip install -r requirements_prod.txt"
    startCommand: "gunicorn -k custom_worker.CustomEventletWorker -w 1 -b 0.0.0.0:$PORT app:app --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.13"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: CORS_ORIGINS
        value: "*"
      - key: LLM_API_KEY
        value: ""